from django.urls import path
from .views import (
    AdminUserCreateView,
    AdminUserDeleteView,
    AdminUserUpdateView,
    RegisterView,
    MyTokenObtainView,
    AdminOnlyView,
    SupervisorOnlyView,
    StudentOnlyView,
    ProfileUpdateView,
    ForgotPasswordView,
    ResetPasswordView,
    VerifyInstitutionEmailView,
    UserActivateDeactivateView,
    UserListView,
    UserDetailView,
    CurrentUserView,
    UsersByRoleView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', MyTokenObtainView.as_view(), name='login'),
    path('admin-data/', AdminOnlyView.as_view(), name='admin-data'),
    path('supervisor-data/', SupervisorOnlyView.as_view(), name='supervisor-data'),
    path('student-data/', StudentOnlyView.as_view(), name='student-data'),
    path('update-profile/', ProfileUpdateView.as_view(), name='update-profile'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('verify-institution-email/<uidb64>/<token>/', VerifyInstitutionEmailView.as_view(), name='verify-institution-email'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/role/<str:role>/', UsersByRoleView.as_view(), name='user-list-by-role'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('admin/users/create/', AdminUserCreateView.as_view(), name='admin-user-create'),
    path('admin/users/<int:pk>/update/', AdminUserUpdateView.as_view(), name='admin-user-update'),
    path('admin/users/<int:pk>/delete/', AdminUserDeleteView.as_view(), name='admin-user-delete'),
    path('admin/users/<int:pk>/toggle-active/', UserActivateDeactivateView.as_view(), name='admin-user-toggle-active'),
    path('me/', CurrentUserView.as_view(), name='current-user'),
]
