# Generated by Django 5.1.7 on 2026-03-20 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapi', '0002_coordinatorprofile_studentprofile_supervisorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('FINAL', 'Final')], max_length=20)),
                ('file', models.FileField(upload_to='reports/')),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapi.studentprofile')),
            ],
        ),
    ]
