# Generated by Django 5.1.7 on 2026-03-20 16:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Message must be at least 5 characters long.')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('general', 'General Communication'), ('alert', 'Alert'), ('instruction', 'Instruction'), ('report', 'Report'), ('request', 'Request')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('attachments', models.JSONField(blank=True, default=dict)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_logs', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sender', 'timestamp'], name='communicati_sender__b72124_idx'), models.Index(fields=['receiver', 'timestamp'], name='communicati_receive_55df0d_idx'), models.Index(fields=['is_read'], name='communicati_is_read_ef9d85_idx'), models.Index(fields=['priority'], name='communicati_priorit_8a8368_idx')],
            },
        ),
    ]
