# Generated by Django 5.1.7 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapi", "0002_coordinatorprofile_studentprofile_supervisorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Optional phone number for account contact",
                max_length=20,
                null=True,
            ),
        ),
    ]

